name = "climax"
version = "0.1.0"
defaultTargets = ["climax"]
testDriver = "test"

[[require]]
name = "colorized"
scope = "algebraic-dev"

[[lean_lib]]
name = "Climax"

[[lean_exe]]
name = "climax-example"
root = "Main"

[[require]]
name = "LSpec"
scope = "argumentcomputer"

[[lean_exe]]
name = "test"
root = "Test.Basic"
